In [21]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [22]:
df=pd.read_csv("D:\homeprices (1).csv")
df.head(3)


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000

In [23]:
df.describe()

area  bedrooms        age          price
count     6.000000   5.00000   6.000000       6.000000
mean   3416.666667   4.20000  16.500000  648333.333333
std     587.934237   1.30384   8.288546  109117.673484
min    2600.000000   3.00000   8.000000  550000.000000
25%    3050.000000   3.00000   9.750000  572500.000000
50%    3400.000000   4.00000  16.500000  602500.000000
75%    3900.000000   5.00000  19.500000  722500.000000
max    4100.000000   6.00000  30.000000  810000.000000

In [24]:
import math
median_bedroom= math.floor(df.bedrooms.median())
median_bedroom

4

In [27]:
df.bedrooms=df.bedrooms.fillna(median_bedroom)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [28]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [30]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [31]:
reg.intercept_

221323.0018654043

In [35]:
reg.predict([[3000,3,40]])

C:\Users\suaru\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [36]:
112.06244194*3000+23388.88007794*3+-3231.71790863*40+221323.0018654043

498408.2515740243

In [72]:
rf=pd.read_csv("D:\hiring (1).csv")
rf

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [73]:
# Create a custom mapping dictionary
mapping = {'five': 5, 'two': 2, 'seven': 7,'three':3,'ten':10,'eleven':11}

# Apply the mapping to the 'Category' column
rf['experience_one'] = rf['experience'].map(mapping)
rf

experience  test_score  interview_score  salary  experience_one
0        NaN         8.0                9   50000             NaN
1        NaN         8.0                6   45000             NaN
2       five         6.0                7   60000             5.0
3        two        10.0               10   65000             2.0
4      seven         9.0                6   70000             7.0
5      three         7.0               10   62000             3.0
6        ten         NaN                7   72000            10.0
7     eleven         7.0                8   80000            11.0

In [74]:
rf.drop('experience',axis=1,inplace=True)

In [75]:
rf.describe()

test_score  interview_score       salary  experience_one
count    7.000000         8.000000      8.00000        6.000000
mean     7.857143         7.875000  63000.00000        6.333333
std      1.345185         1.642081  11501.55269        3.669696
min      6.000000         6.000000  45000.00000        2.000000
25%      7.000000         6.750000  57500.00000        3.500000
50%      8.000000         7.500000  63500.00000        6.000000
75%      8.500000         9.250000  70500.00000        9.250000
max     10.000000        10.000000  80000.00000       11.000000

In [81]:
import math
mean_exp1=math.floor(rf.experience_one.mean())
mean_inter1=math.floor(rf.interview_score.mean())
mean_test1=math.floor(rf.test_score.mean())


In [82]:
rf.experience_one=rf.experience_one.fillna(mean_exp)
rf.interview_score=rf.interview_score.fillna(mean_inter1)
rf.test_score=rf.test_score.fillna(mean_test1)
rf

test_score  interview_score  salary  experience_one
0         8.0                9   50000             6.0
1         8.0                6   45000             6.0
2         6.0                7   60000             5.0
3        10.0               10   65000             2.0
4         9.0                6   70000             7.0
5         7.0               10   62000             3.0
6         7.0                7   72000            10.0
7         7.0                8   80000            11.0

In [84]:
ref=linear_model.LinearRegression()
ref.fit(rf[['test_score','interview_score','experience_one']],rf.salary)

LinearRegression()

In [85]:
ref.predict([[8,9,6]])

C:\Users\suaru\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([65897.22668645])

In [86]:
ref.coef_


array([1225.36778341, 2941.77277785, 2874.43853793])

In [87]:
ref.intercept_

12371.698190958938

In [89]:
1225.36778341*8+2941.77277785*9+2874.43853793*6+12371.698190958938

65897.22668646893